export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const NEW_LOCATION = "NEW_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION = "EDIT_LOCATION";
